package com.ugreen.unlock;

/**
 * GENERATED FILE - do not edit by hand.
 * Source: module/js/unlock_payload.js  (regenerate with tools/gen_payload.py)
 */
public final class JsPayload {

    private JsPayload() {
    }

    public static final String JS = "/*\n"
            + " * UGREEN HiTune Unlock — injected WebView payload\n"
            + " * ------------------------------------------------------------------\n"
            + " * Injected into the \"device detail\" H5 page of com.ugreen.iot\n"
            + " * (file:///android_asset/static/device/index.html).\n"
            + " *\n"
            + " * Background\n"
            + " *   The page keeps the whole per-model capability table inside the\n"
            + " *   bundled chunk assets/index-*.js (an axios-mock-adapter answers\n"
            + " *   POST /earbuds/device_info straight from a local table; no network).\n"
            + " *   On boot the page calls  earPhoneStore.setConfig(device_info),\n"
            + " *   which shallow-merges the *reduced* per-model option lists over the\n"
            + " *   store defaults -- that merge is the only thing gating the UI.\n"
            + " *\n"
            + " *   e.g. UGREEN HiTune S5 -> is_left_ear_single_tap_options = [none, play_pause]\n"
            + " *        UGREEN HiTune S8 -> (key absent) -> defaults to [none, play_pause, vol+, vol-]\n"
            + " *\n"
            + " * What this does\n"
            + " *   1) hooks earPhoneStore.setConfig so every future merge keeps the full\n"
            + " *      option list, and\n"
            + " *   2) overwrites the live config's option lists with the full set, and\n"
            + " *   3) forces the 12 row-visibility flags on.\n"
            + " *\n"
            + " * The page renders whatever is in those arrays, so every gesture\n"
            + " * (single / double / triple / long press, per ear and per button) then\n"
            + " * offers every action the protocol understands.\n"
            + " *\n"
            + " * Note: whether the earbud *firmware* honours a given action is a\n"
            + " * separate question -- this only removes the app-side restriction.\n"
            + " * The wire format is a fixed 8-byte payload\n"
            + " * [leftSingle, leftDouble, leftTriple, leftLong,\n"
            + " *  rightSingle, rightDouble, rightTriple, rightLong]\n"
            + " * so all slots are always transmitted; the app just never let you pick.\n"
            + " */\n"
            + "(function () {\n"
            + "  'use strict';\n"
            + "\n"
            + "  var FLAG = '__UG_HITUNE_UNLOCK_V1__';\n"
            + "  if (window[FLAG]) return;\n"
            + "  window[FLAG] = true;\n"
            + "\n"
            + "  var TAG = '[UGUnlock] ';\n"
            + "\n"
            + "  // ---- status channel -----------------------------------------------\n"
            + "  // console.log does NOT reach logcat in this app (the WebView does not\n"
            + "  // enable chromium console logging), so the same information is also kept\n"
            + "  // in a ring buffer and exposed through a global. The Java side reads it\n"
            + "  // back as the return value of evaluateJavascript, which makes the payload\n"
            + "  // observable without any WebView debug setup.\n"
            + "  var LOGBUF = [];\n"
            + "\n"
            + "  function log() {\n"
            + "    try {\n"
            + "      LOGBUF.push(Array.prototype.slice.call(arguments).join(' '));\n"
            + "      if (LOGBUF.length > 60) LOGBUF.shift();\n"
            + "      console.log.apply(console, [TAG].concat(Array.prototype.slice.call(arguments)));\n"
            + "    } catch (e) { /* ignore */ }\n"
            + "  }\n"
            + "\n"
            + "  // Deliberately re-runs apply(): it is idempotent, so this doubles as a\n"
            + "  // \"is everything still unlocked?\" check.\n"
            + "  window.__UG_UNLOCK_STATUS__ = function () {\n"
            + "    var hasStore = false;\n"
            + "    var ok = false;\n"
            + "    var sig = '-';\n"
            + "    var proto = '-';\n"
            + "    var hooked = false;\n"
            + "    try {\n"
            + "      var st = findStore();\n"
            + "      hasStore = !!st;\n"
            + "      if (st) {\n"
            + "        hooked = !!st.__ugUnlockHooked;\n"
            + "        if (st.config) {\n"
            + "          proto = (st.config.protocol_type === undefined) ? '-' : st.config.protocol_type;\n"
            + "          ok = !!apply();\n"
            + "          sig = signature(buildFull(st.config)) || '-';\n"
            + "        }\n"
            + "      }\n"
            + "    } catch (e) {\n"
            + "      return 'ERR ' + e;\n"
            + "    }\n"
            + "    return 'flag=1 store=' + (hasStore ? 1 : 0)\n"
            + "      + ' hooked=' + (hooked ? 1 : 0)\n"
            + "      + ' ok=' + (ok ? 1 : 0)\n"
            + "      + ' proto=' + proto\n"
            + "      + ' sig=' + sig\n"
            + "      + ' diag=' + DIAG\n"
            + "      + ' log=' + LOGBUF.slice(-6).join(' | ');\n"
            + "  };\n"
            + "\n"
            + "  // ---- action type tables -------------------------------------------\n"
            + "  // UNIVERSAL (UGREEN_Universal, protocol_type == 1) numbering\n"
            + "  var UNIV_ORDER = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 11];\n"
            + "  var UNIV_LABEL = {\n"
            + "    0: 'none', 1: 'play_pause', 2: 'increase_volume', 3: 'decrease_volume',\n"
            + "    4: 'next_track', 5: 'previous_track', 6: 'voice_assistant',\n"
            + "    7: 'game_mode_music_mode', 8: 'noise_control1', 9: 'answer_hang_up',\n"
            + "    11: 'spatial_audio_music_mode',\n"
            + "    12: 'AI_dialogue', 13: 'AI_chat', 14: 'AI_recording'\n"
            + "  };\n"
            + "\n"
            + "  // MAGIC (Zhongke_Lanxun / BlueTrum, protocol_type == 2) numbering\n"
            + "  var MAGIC_ORDER = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9];\n"
            + "  var MAGIC_LABEL = {\n"
            + "    0: 'none', 1: null, 2: 'voice_assistant', 3: 'previous_track',\n"
            + "    4: 'next_track', 5: 'increase_volume', 6: 'decrease_volume',\n"
            + "    7: 'play_pause', 8: 'game_mode', 9: 'noise_control1',\n"
            + "    12: 'AI_dialogue', 13: 'AI_chat', 14: 'AI_recording'\n"
            + "  };\n"
            + "  // the page itself hardcodes this one (see MAPPINGMAGIC)\n"
            + "  var MAGIC_LITERAL = { 1: '回拨电话' };\n"
            + "\n"
            + "  var AI_ORDER = [12, 13, 14];\n"
            + "\n"
            + "  var OPTION_KEYS = [\n"
            + "    'is_left_ear_single_tap_options',\n"
            + "    'is_left_ear_single_double_options',\n"
            + "    'is_left_ear_single_triple_options',\n"
            + "    'is_left_ear_single_long_options',\n"
            + "    'is_right_ear_single_tap_options',\n"
            + "    'is_right_ear_single_double_options',\n"
            + "    'is_right_ear_single_triple_options',\n"
            + "    'is_right_ear_single_long_options',\n"
            + "    'is_ANC_ear_single_tap_options',\n"
            + "    'is_ANC_ear_single_double_options',\n"
            + "    'is_ANC_ear_single_triple_options',\n"
            + "    'is_ANC_ear_single_long_options',\n"
            + "    'is_volume_add_ear_single_tap_options',\n"
            + "    'is_volume_minus_ear_single_tap_options'\n"
            + "  ];\n"
            + "\n"
            + "  var ROW_FLAGS = [\n"
            + "    'is_left_ear_single_tap', 'is_left_ear_double_tap',\n"
            + "    'is_left_ear_triple_tap', 'is_left_ear_long_press',\n"
            + "    'is_right_ear_single_tap', 'is_right_ear_double_tap',\n"
            + "    'is_right_ear_triple_tap', 'is_right_ear_long_press',\n"
            + "    'is_ANC_ear_single_tap', 'is_ANC_ear_double_tap',\n"
            + "    'is_ANC_ear_triple_tap', 'is_ANC_ear_long_press'\n"
            + "  ];\n"
            + "\n"
            + "  // ---- Vue / Pinia discovery ----------------------------------------\n"
            + "  var _app = null, _pinia = null, _store = null;\n"
            + "  var DIAG = '';\n"
            + "\n"
            + "  function findApp() {\n"
            + "    if (_app) return _app;\n"
            + "    try {\n"
            + "      var el = document.getElementById('app') || document.body;\n"
            + "      if (el && el.__vue_app__) {\n"
            + "        _app = el.__vue_app__;\n"
            + "        return _app;\n"
            + "      }\n"
            + "      var all = document.querySelectorAll('*');\n"
            + "      for (var i = 0; i < all.length; i++) {\n"
            + "        if (all[i].__vue_app__) {\n"
            + "          _app = all[i].__vue_app__;\n"
            + "          return _app;\n"
            + "        }\n"
            + "      }\n"
            + "    } catch (e) { /* ignore */ }\n"
            + "    return null;\n"
            + "  }\n"
            + "\n"
            + "  function findPinia() {\n"
            + "    if (_pinia) return _pinia;\n"
            + "    var app = findApp();\n"
            + "    if (!app) return null;\n"
            + "    try {\n"
            + "      var gp = app.config && app.config.globalProperties;\n"
            + "      if (gp && gp.$pinia) {\n"
            + "        _pinia = gp.$pinia;\n"
            + "        return _pinia;\n"
            + "      }\n"
            + "    } catch (e) { /* ignore */ }\n"
            + "    try {\n"
            + "      var prov = app._context && app._context.provides;\n"
            + "      if (prov) {\n"
            + "        var syms = Object.getOwnPropertySymbols(prov);\n"
            + "        for (var i = 0; i < syms.length; i++) {\n"
            + "          var v = prov[syms[i]];\n"
            + "          if (v && v._s && typeof v._s.get === 'function') {\n"
            + "            _pinia = v;\n"
            + "            return _pinia;\n"
            + "          }\n"
            + "        }\n"
            + "      }\n"
            + "    } catch (e) { /* ignore */ }\n"
            + "    return null;\n"
            + "  }\n"
            + "\n"
            + "  function findStore() {\n"
            + "    if (_store && _store.config) return _store;\n"
            + "    var pinia = findPinia();\n"
            + "    if (!pinia) {\n"
            + "      DIAG = 'noPinia(app=' + (findApp() ? 1 : 0) + ')';\n"
            + "      return null;\n"
            + "    }\n"
            + "    if (!pinia._s) {\n"
            + "      DIAG = 'pinia-no-_s';\n"
            + "      return null;\n"
            + "    }\n"
            + "    var s = null;\n"
            + "    try {\n"
            + "      s = pinia._s.get('earPhoneStore');\n"
            + "    } catch (e) { /* ignore */ }\n"
            + "    if (!s || !s.config) {\n"
            + "      s = null;\n"
            + "      try {\n"
            + "        var names = [];\n"
            + "        pinia._s.forEach(function (st, key) {\n"
            + "          names.push(key);\n"
            + "          if (!s && st && st.config &&\n"
            + "              typeof st.config.is_left_ear_single_tap_options !== 'undefined') {\n"
            + "            s = st;\n"
            + "          }\n"
            + "        });\n"
            + "        DIAG = 'stores[' + names.join(',') + ']';\n"
            + "      } catch (e) { DIAG = 'scanErr:' + e; }\n"
            + "    }\n"
            + "    if (s && s.config) _store = s;\n"
            + "    return _store;\n"
            + "  }\n"
            + "\n"
            + "  function translate(key) {\n"
            + "    if (!key) return null;\n"
            + "    try {\n"
            + "      var app = findApp();\n"
            + "      var gp = app && app.config && app.config.globalProperties;\n"
            + "      if (gp && typeof gp.$t === 'function') {\n"
            + "        var v = gp.$t('earphone.control.' + key);\n"
            + "        if (typeof v === 'string' && v && v.indexOf('earphone.control.') !== 0) return v;\n"
            + "      }\n"
            + "    } catch (e) { /* ignore */ }\n"
            + "    return null;\n"
            + "  }\n"
            + "\n"
            + "  // ---- build the full option list -----------------------------------\n"
            + "  function harvestLabels(cfg) {\n"
            + "    var pool = {};\n"
            + "    var keys = Object.keys(cfg);\n"
            + "    for (var i = 0; i < keys.length; i++) {\n"
            + "      if (!/options$/.test(keys[i])) continue;\n"
            + "      var arr = cfg[keys[i]];\n"
            + "      if (!Array.isArray(arr)) continue;\n"
            + "      for (var j = 0; j < arr.length; j++) {\n"
            + "        var o = arr[j];\n"
            + "        if (o && typeof o.type === 'number' && pool[o.type] === undefined &&\n"
            + "            typeof o.label === 'string' && o.label) {\n"
            + "          pool[o.type] = o.label;\n"
            + "        }\n"
            + "      }\n"
            + "    }\n"
            + "    return pool;\n"
            + "  }\n"
            + "\n"
            + "  function buildFull(cfg) {\n"
            + "    var magic = cfg.protocol_type === 2;\n"
            + "    var pool = harvestLabels(cfg);\n"
            + "    var order = (magic ? MAGIC_ORDER : UNIV_ORDER).slice();\n"
            + "    var labelMap = magic ? MAGIC_LABEL : UNIV_LABEL;\n"
            + "\n"
            + "    var hasAi = false;\n"
            + "    for (var i = 0; i < OPTION_KEYS.length; i++) {\n"
            + "      var arr = cfg[OPTION_KEYS[i]];\n"
            + "      if (!Array.isArray(arr)) continue;\n"
            + "      for (var j = 0; j < arr.length; j++) {\n"
            + "        var ty = arr[j] && arr[j].type;\n"
            + "        if (ty === 12 || ty === 13 || ty === 14) hasAi = true;\n"
            + "      }\n"
            + "    }\n"
            + "    if (hasAi) order = order.concat(AI_ORDER);\n"
            + "\n"
            + "    var out = [];\n"
            + "    for (var n = 0; n < order.length; n++) {\n"
            + "      var type = order[n];\n"
            + "      var label = null;\n"
            + "      if (magic) {\n"
            + "        // magic numbering is incompatible with the universal defaults that\n"
            + "        // refreshLanguage() writes, so translate by key first\n"
            + "        label = translate(labelMap[type]);\n"
            + "        if (!label && MAGIC_LITERAL[type]) label = MAGIC_LITERAL[type];\n"
            + "        if (!label && pool[type] !== undefined) label = pool[type];\n"
            + "      } else {\n"
            + "        label = pool[type] !== undefined ? pool[type] : translate(labelMap[type]);\n"
            + "      }\n"
            + "      if (!label) label = labelMap[type] ? labelMap[type] : String(type);\n"
            + "      out.push({ label: label, type: type });\n"
            + "    }\n"
            + "    return out;\n"
            + "  }\n"
            + "\n"
            + "  function signature(arr) {\n"
            + "    if (!Array.isArray(arr)) return '';\n"
            + "    var s = [];\n"
            + "    for (var i = 0; i < arr.length; i++) s.push(arr[i] && arr[i].type);\n"
            + "    return s.join(',');\n"
            + "  }\n"
            + "\n"
            + "  function clone(arr) {\n"
            + "    var out = [];\n"
            + "    for (var i = 0; i < arr.length; i++) out.push({ label: arr[i].label, type: arr[i].type });\n"
            + "    return out;\n"
            + "  }\n"
            + "\n"
            + "  function stampInto(target, full) {\n"
            + "    for (var i = 0; i < OPTION_KEYS.length; i++) target[OPTION_KEYS[i]] = clone(full);\n"
            + "    for (var j = 0; j < ROW_FLAGS.length; j++) target[ROW_FLAGS[j]] = true;\n"
            + "  }\n"
            + "\n"
            + "  // ---- apply --------------------------------------------------------\n"
            + "  function apply() {\n"
            + "    var store = findStore();\n"
            + "    if (!store) return false;\n"
            + "    var cfg = store.config;\n"
            + "    if (!cfg) return false;\n"
            + "\n"
            + "    // (1) one-time: keep the full lists across every future setConfig()\n"
            + "    if (!store.__ugUnlockHooked) {\n"
            + "      var orig = store.setConfig;\n"
            + "      if (typeof orig === 'function') {\n"
            + "        try {\n"
            + "          store.setConfig = function (incoming) {\n"
            + "            try {\n"
            + "              if (incoming && typeof incoming === 'object') {\n"
            + "                var merged = {};\n"
            + "                var base = (this && this.config) || cfg;\n"
            + "                var k;\n"
            + "                for (k in base) {\n"
            + "                  if (Object.prototype.hasOwnProperty.call(base, k) && !isFn(base[k])) merged[k] = base[k];\n"
            + "                }\n"
            + "                for (k in incoming) {\n"
            + "                  if (Object.prototype.hasOwnProperty.call(incoming, k)) merged[k] = incoming[k];\n"
            + "                }\n"
            + "                stampInto(incoming, buildFull(merged));\n"
            + "              }\n"
            + "            } catch (err) {\n"
            + "              log('setConfig pre-patch failed', err);\n"
            + "            }\n"
            + "            return orig.apply(this, arguments);\n"
            + "          };\n"
            + "          store.__ugUnlockHooked = true;\n"
            + "          log('setConfig hooked');\n"
            + "        } catch (e) { log('cannot hook setConfig', e); }\n"
            + "      }\n"
            + "    }\n"
            + "\n"
            + "    // (2) fix whatever config is live right now\n"
            + "    var full, sig;\n"
            + "    try {\n"
            + "      full = buildFull(cfg);\n"
            + "      sig = signature(full);\n"
            + "    } catch (e2) {\n"
            + "      log('buildFull failed', e2);\n"
            + "      return false;\n"
            + "    }\n"
            + "    if (!full || !full.length) return false;\n"
            + "\n"
            + "    var changed = false;\n"
            + "    for (var a = 0; a < OPTION_KEYS.length; a++) {\n"
            + "      var key = OPTION_KEYS[a];\n"
            + "      if (signature(cfg[key]) !== sig) {\n"
            + "        cfg[key] = clone(full);\n"
            + "        changed = true;\n"
            + "      }\n"
            + "    }\n"
            + "    for (var b = 0; b < ROW_FLAGS.length; b++) {\n"
            + "      if (cfg[ROW_FLAGS[b]] !== true) {\n"
            + "        cfg[ROW_FLAGS[b]] = true;\n"
            + "        changed = true;\n"
            + "      }\n"
            + "    }\n"
            + "    if (changed) {\n"
            + "      log('unlocked ' + (cfg.protocol_type === 2 ? 'MAGIC' : 'UNIVERSAL') + ' -> ' + sig);\n"
            + "    }\n"
            + "    return true;\n"
            + "  }\n"
            + "\n"
            + "  function isFn(v) {\n"
            + "    return typeof v === 'function';\n"
            + "  }\n"
            + "\n"
            + "  // ---- retry loop ---------------------------------------------------\n"
            + "  // The page mounts and fetches its config asynchronously, so keep poking\n"
            + "  // until the store shows up (and re-assert for a while afterwards).\n"
            + "  var tries = 0;\n"
            + "  var timer = setInterval(function () {\n"
            + "    tries++;\n"
            + "    var ok = false;\n"
            + "    try { ok = apply(); } catch (e) { log('loop error', e); }\n"
            + "    if (tries > 1200) {\n"
            + "      clearInterval(timer);\n"
            + "      log('stopped after ' + tries + ' tries (ok=' + ok + ')');\n"
            + "    }\n"
            + "  }, 500);\n"
            + "\n"
            + "  try { apply(); } catch (e) { /* ignore */ }\n"
            + "\n"
            + "  window.__UG_UNLOCK_APPLY__ = apply;\n"
            + "})();\n"
            + "";
}
