#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Extract real config fixtures out of the app's device-page JS bundle.

Produces test/fixtures.js with:
  DEFAULTS  - the earPhoneStore default config (has the full option lists)
  S5 / S8   - the per-model device_info the app actually merges over it
so the injected payload can be exercised against real data.

The bundle filename contains a content hash (index-DSOWORxZ.js) that changes
whenever the app is rebuilt, so it is discovered by glob rather than hardcoded.
Run tools/extract_apk.py first to populate work/extract.
"""
import glob
import io
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
BUNDLE_DIR = os.path.join(ROOT, '..', 'work', 'extract', 'assets', 'static',
                          'device', 'assets')
OUT = os.path.join(ROOT, 'test', 'fixtures.js')


def find_bundle():
    """Locate the modern (non-legacy) device-page bundle."""
    pats = [os.path.join(BUNDLE_DIR, 'index-*.js')]
    for pat in pats:
        cands = [p for p in sorted(glob.glob(pat))
                 if 'legacy' not in os.path.basename(p)]
        if cands:
            return cands[0]
    return None


def balanced(text, start):
    """text[start] must be '{' or '['; return the balanced slice."""
    open_ch = text[start]
    close_ch = '}' if open_ch == '{' else ']'
    depth = 0
    i = start
    n = len(text)
    while i < n:
        c = text[i]
        if c in '"\'':
            quote = c
            i += 1
            while i < n:
                if text[i] == '\\':
                    i += 2
                    continue
                if text[i] == quote:
                    break
                i += 1
        elif c in '{[':
            depth += 1
        elif c in '}]':
            depth -= 1
            if depth == 0:
                return text[start:i + 1]
        i += 1
    raise ValueError('unbalanced')


def main():
    src_path = find_bundle()
    if not src_path:
        sys.exit('device bundle not found under %s\n'
                 'Run this first:  python tools/extract_apk.py' % BUNDLE_DIR)
    bundle_name = os.path.basename(src_path)

    src = io.open(src_path, encoding='utf-8', errors='replace').read()

    # 1) store defaults:  state:()=>({config:{ ... },game_switch:
    m = re.search(r'state:\(\)=>\(\{config:\{', src)
    if not m:
        sys.exit('store defaults not found in %s -- app layout changed' % bundle_name)
    cfg_start = src.index('{', m.start() + len('state:()=>({config:'))
    defaults = balanced(src, cfg_start)

    # 2) per-model device_info blocks
    models = {}
    for name in ('UGREEN HiTune S5', 'UGREEN HiTune S8'):
        cm = re.search(r'case"' + re.escape(name) + r'":a=\[200,\{token:"[^"]*",device_info:\{', src)
        if not cm:
            sys.exit('model not found in %s: %s' % (bundle_name, name))
        di_start = src.index('{', cm.end() - 1)
        models[name] = balanced(src, di_start)

    out = io.StringIO()
    out.write('// GENERATED by module/tools/extract_fixtures.py - do not edit.\n')
    out.write('// Real data lifted from the app bundle '
              'assets/static/device/assets/%s\n' % bundle_name)
    out.write('/* eslint-disable */\n')
    out.write('function Ue(k) { return k; }\n')
    out.write('function jn() { return false; }\n')
    out.write('var n = Ue; /* the per-model table uses n() for translate */\n')
    out.write('var en = { UGREEN_Universal: 1, Zhongke_Lanxun: 2 };\n')
    out.write('var DEFAULTS = ' + defaults + ';\n')
    out.write('var MODEL_S5 = ' + models['UGREEN HiTune S5'] + ';\n')
    out.write('var MODEL_S8 = ' + models['UGREEN HiTune S8'] + ';\n')
    out.write('module.exports = { Ue: Ue, jn: jn, DEFAULTS: DEFAULTS, '
              'MODEL_S5: MODEL_S5, MODEL_S8: MODEL_S8 };\n')

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    io.open(OUT, 'w', encoding='utf-8', newline='\n').write(out.getvalue())
    print('wrote %s (from %s; defaults %d chars, S5 %d, S8 %d)'
          % (OUT, bundle_name, len(defaults), len(models['UGREEN HiTune S5']),
             len(models['UGREEN HiTune S8'])))


if __name__ == '__main__':
    main()
